---
language: node_js
node_js:
  - '0.10'
services:
  - neo4j
before_script:
  - npm install -g grunt-cli
after_script:
#  - wget -qO- https://toolbelt.heroku.com/install-ubuntu.sh | sh
#  - git remote add heroku git@heroku.com:movie-database-node.git
#  - echo "Host heroku.com" >> ~/.ssh/config
#  - echo "   StrictHostKeyChecking no" >> ~/.ssh/config
#  - echo "   CheckHostIP no" >> ~/.ssh/config
#  - echo "   UserKnownHostsFile=/dev/null" >> ~/.ssh/config
#  - heroku keys:clear
#  - yes | heroku keys:add
#  - yes | git push heroku master
env:
  global:
  - secure: ! 'oMQE0FSPxyi0G/eMlt6NRFfaKuEVQjcY/e28N/lncoIwb8hGylXjnmaQ6/ME
      eicggmI+KJmrDJhz/O2KezoyyBDGABr8RhnilZ5cYQZyvorqsKJfnjw3kClG
      TuLFRS+9XTi17m4ybUJGTYnBBhadX3csDuTuCj8+eh9vmnD9oGM='

